spring:
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:password}

  data:
    neo4j:
      database: ${NEO4J_DATABASE:neo4j}

server:
  port: 8080

bookfinder:
  data:
    dir: ${DATA_DIR:./data}
    books-file: goodreads_books_young_adult.json
    interactions-file: goodreads_interactions_young_adult.json
    reviews-file: goodreads_reviews_young_adult.json
    subset-size: 10000
    max-interactions: 50000
    max-reviews: 50000
    batch-size: 500
